# Configuration file for tmux >= 2.1
# .tmux.conf gets automatically read if in user directory (~)

# use 256 colour terminal:
set -g default-terminal "screen-256color"

# enable mouse:
set -g mouse on

# pane movement
bind-key j command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:" "join-pane -t '%%'"

# pane splitting
unbind '"'
unbind %
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pante_current_path}"
